# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2662de847986266a06bf7baab338547f6ac4c9e2d9dd26998db5ecc95ecf7f0e6ec0dd85c3a4f5ec965585e4244607055910efc8b19138c3b8b27ead0dd2b2a2

test:
  secret_key_base: 0da27289c2109aefa15dcfc6ceda276f54df181ee0112072d6b653040b20c2ac2b5d860e97bd6d0ccc595ef1ceb773b72e4009573f3b9b526f39edf9055435b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
